---
Name: shopconfig
After: framework/routes#coreroutes
---
SilverShop\Core\ShopConfig:
  base_currency: NZD
Member:
  login_joins_cart: true
SilverShop\Core\Product_Image:
  thumbnail_width: 140
  thumbnail_height: 100
  content_image_width: 200
  large_image_width: 600
SilverShop\Core\OrderProcessor:
  bcc_receipt_to_admin: true
Injector:
  SilverShop\Core\CheckoutComponentConfig:
    class: SilverShop\Core\SinglePageCheckoutComponentConfig
  ShopEmail:
    class: StyledHtmlEmail
LeftAndMain:
  extra_requirements_css:
    - silvershop/css/shopcms.css
